export const academicTask1Templates = [
  {
    title: 'Line graph',
    tag: 'Change over time',
    useWhen: 'One or more lines show how figures change across dates or periods.',
    plan: [
      ['Introduction', 'The line graph illustrates how [measure] changed in [place/group] between [start year] and [end year].'],
      ['Overview', 'Overall, [A] showed an upward/downward trend, whereas [B] moved in the opposite direction/remained comparatively stable. The most striking feature is that [highest point, largest change or crossover].'],
      ['Details 1', 'In [start year], [A] stood at [figure], compared with [B] at [figure]. [A] then rose/fell [degree] to [figure] by [year], while [B] [movement].'],
      ['Details 2', 'From [year] onwards, [remaining trend or comparison]. By the end of the period, [final ranking/comparison], at [figures], respectively.'],
    ],
    examiner: 'Group lines by a shared trend or by meaningful comparison; do not narrate every year.',
  },
  {
    title: 'Bar chart',
    tag: 'Comparison or change',
    useWhen: 'Bars compare categories at one time or across several times.',
    plan: [
      ['Introduction', 'The bar chart compares [categories] in terms of [measure] in [place/time].'],
      ['Overview', 'Overall, [largest category/general pattern]. By contrast, [smallest category/opposing pattern]. [Mention a major similarity or change if relevant].'],
      ['Details 1', '[A] recorded the highest figure, at [number], followed by [B] at [number]. The corresponding figures for [C and D] were [numbers].'],
      ['Details 2', 'By comparison, [remaining categories]. [A] was approximately twice/three times as high as [B], while the gap between [C] and [D] was only [number].'],
    ],
    examiner: 'Decide whether the chart is static or dynamic before choosing comparison or trend language.',
  },
  {
    title: 'Pie chart',
    tag: 'Proportion',
    useWhen: 'Circles show how a total is divided, sometimes at two different times.',
    plan: [
      ['Introduction', 'The pie chart(s) show(s) the proportions of [total] accounted for by [categories] in [place/year(s)].'],
      ['Overview', 'Overall, [A] made up the largest share, while [B] represented the smallest. Across the period, the distribution became [more/less balanced], mainly because [major shift].'],
      ['Details 1', 'In [year], [A] accounted for [x]%, compared with [B] at [y]%. Together, [C and D] represented [combined share].'],
      ['Details 2', 'By [later year], the proportion of [A] had risen/fallen by [amount] percentage points to [final figure], whereas [B] [change].'],
    ],
    examiner: 'A change from 20% to 30% is 10 percentage points, not a 10% increase.',
  },
  {
    title: 'Table',
    tag: 'Dense data',
    useWhen: 'Rows and columns present several comparable figures.',
    plan: [
      ['Introduction', 'The table provides information about [measure] for [groups/places] in [time].'],
      ['Overview', 'Overall, [highest/lowest or broad pattern]. It is also clear that [second major comparison, exception or change].'],
      ['Details 1', 'Looking first at [logical group], [A] had [figure], while the values for [B] and [C] were [figures]. [Meaningful comparison].'],
      ['Details 2', 'Turning to [second group], [key figures and comparisons]. The most notable gap/change was seen in [category].'],
    ],
    examiner: 'Convert the table into two clear comparison groups; do not reproduce it cell by cell.',
  },
  {
    title: 'Mixed visuals',
    tag: 'Two linked sources',
    useWhen: 'Two charts, tables or diagrams describe related information.',
    plan: [
      ['Introduction', 'The [first visual] shows [what], while the [second visual] provides information about [what].'],
      ['Overview', 'Overall, [main feature from visual 1]. Meanwhile, [main feature from visual 2]. Where relevant, [state the broad relationship between them].'],
      ['Details 1', 'According to the [first visual], [selected key figures/comparisons].'],
      ['Details 2', 'The [second visual] shows that [selected key figures/comparisons], with [important relationship or contrast].'],
    ],
    examiner: 'Give both visuals adequate coverage. A shared overview is usually clearer than two mini-reports.',
  },
  {
    title: 'Man-made process',
    tag: 'Linear stages',
    useWhen: 'A product or material moves through a sequence of manufactured stages.',
    plan: [
      ['Introduction', 'The diagram illustrates how [product] is produced/manufactured from [input].'],
      ['Overview', 'Overall, this is a [linear/cyclical] process consisting of [number] main stages, beginning with [first stage] and ending with [final product/stage].'],
      ['Details 1', 'Initially, [input] is [passive verb]. It is then [next action], after which [next stage].'],
      ['Details 2', 'Once [condition/stage] is complete, [next stages in order]. Finally, [final product] is [stored/transported/used].'],
    ],
    examiner: 'Report every major stage in the correct order. Use the passive where the action matters more than the actor.',
  },
  {
    title: 'Natural cycle',
    tag: 'Life cycle',
    useWhen: 'A natural organism or material changes through repeating stages.',
    plan: [
      ['Introduction', 'The diagram shows the life cycle of [organism] / the natural process by which [phenomenon occurs].'],
      ['Overview', 'Overall, the cycle contains [number] broad stages, beginning with [stage] and eventually returning to [starting stage]. [Mention major environments/forms].'],
      ['Details 1', 'The cycle begins when [active description]. Over the following [time, if shown], [organism/material] [develops/moves/changes].'],
      ['Details 2', 'At the next stage, [sequence]. Eventually, [final mature stage/outcome], after which the cycle begins again.'],
    ],
    examiner: 'Active verbs often sound more natural for living things; include time and location only when the diagram provides them.',
  },
  {
    title: 'Map or plan',
    tag: 'Past or proposed change',
    useWhen: 'Two or more maps show an area before and after development.',
    plan: [
      ['Introduction', 'The maps compare the layout of [place] in [earlier year] and [later year] / show the proposed redevelopment of [place].'],
      ['Overview', 'Overall, the area became/will become [more residential, accessible or developed]. The main changes were/will be [A] and [B], while [retained feature] remained/will remain unchanged.'],
      ['Details 1', 'In [earlier year], [feature] was located [position]. [Nearby features and layout].'],
      ['Details 2', 'By [later year], [feature] had been/will be replaced by [new feature], while a new [feature] had been/will be constructed [location].'],
    ],
    examiner: 'Match the tense to the dates: past changes, present layouts, or proposed future development.',
  },
]

export const generalTask1Templates = [
  {
    title: 'Formal complaint',
    tag: 'Unknown recipient',
    useWhen: 'You write to a company, authority, manager or person you do not know.',
    plan: [
      ['Greeting', 'Dear Sir or Madam,'],
      ['Purpose', 'I am writing to complain about [product/service/situation], which [brief factual problem].'],
      ['Bullet 1', 'On [date], [relevant background and what happened].'],
      ['Bullet 2', 'This caused [specific problem and consequence]. I was particularly disappointed because [reasonable explanation].'],
      ['Bullet 3 / action', 'I would therefore appreciate it if you could [requested action]. I would be grateful for a response by [reasonable time, if useful].'],
      ['Sign-off', 'Yours faithfully,\n[Full name]'],
    ],
    examiner: 'Be firm but polite. Anger, threats and slang usually make the tone inappropriate.',
  },
  {
    title: 'Formal request or information',
    tag: 'Service, course or authority',
    useWhen: 'You ask an organisation for information, permission or action.',
    plan: [
      ['Greeting', 'Dear Sir or Madam,'],
      ['Purpose', 'I am writing to enquire about / request [topic].'],
      ['Bullet 1', 'I am currently [relevant background], and I am interested in [specific subject].'],
      ['Bullet 2', 'Could you please let me know [question 1]? I would also like to find out whether [question 2].'],
      ['Bullet 3 / action', 'I would be grateful if you could [send/confirm/arrange] [detail]. I look forward to your response.'],
      ['Sign-off', 'Yours faithfully,\n[Full name]'],
    ],
    examiner: 'Turn every bullet point into adequately developed content, not a one-sentence checklist.',
  },
  {
    title: 'Formal application',
    tag: 'Job, course or programme',
    useWhen: 'You apply for an advertised opportunity or ask to be considered.',
    plan: [
      ['Greeting', 'Dear Sir or Madam / Dear Mr or Ms [Surname],'],
      ['Purpose', 'I am writing to apply for [position/course], which I saw advertised [where].'],
      ['Bullet 1', 'I am currently [background], and I have [relevant qualification/experience].'],
      ['Bullet 2', 'In particular, [specific skill or example], which would enable me to [relevance].'],
      ['Bullet 3 / action', 'I am available [details] and would welcome the opportunity to [interview/discuss]. Thank you for considering my application.'],
      ['Sign-off', 'Yours sincerely,\n[Full name]'],
    ],
    examiner: 'Use Yours sincerely when the greeting names the recipient; use Yours faithfully when it does not.',
  },
  {
    title: 'Semi-formal problem or request',
    tag: 'Known professional contact',
    useWhen: 'You know the person, but the relationship is professional: a teacher, landlord, neighbour or manager.',
    plan: [
      ['Greeting', 'Dear Mr or Ms [Surname],'],
      ['Purpose', 'I am writing about [situation]. I was hoping you might be able to [request/purpose].'],
      ['Bullet 1', 'As you may know, [relevant background].'],
      ['Bullet 2', 'The main difficulty is that [problem + effect].'],
      ['Bullet 3 / action', 'Would it be possible to [requested solution]? I would be happy to [reasonable cooperation].'],
      ['Sign-off', 'Kind regards / Yours sincerely,\n[Full name]'],
    ],
    examiner: 'Warm and respectful is safer than either highly legal language or chatty slang.',
  },
  {
    title: 'Informal invitation',
    tag: 'Friend or relative',
    useWhen: 'You invite someone, explain arrangements and encourage them to come.',
    plan: [
      ['Greeting', 'Dear [First name],'],
      ['Purpose', "I'm writing to invite you to [event]. It would be great if you could come!"],
      ['Bullet 1', 'The [event] is going to take place [time/place], and [useful details].'],
      ['Bullet 2', 'You can [travel/stay/bring something], so [reassurance or arrangement].'],
      ['Bullet 3', "I really hope you can make it because [personal reason]. Let me know what you think."],
      ['Sign-off', 'Best wishes / All the best,\n[First name]'],
    ],
    examiner: 'Contractions and friendly phrases are natural, but the message still needs clear paragraphs and full bullet coverage.',
  },
  {
    title: 'Informal apology',
    tag: 'Friend or relative',
    useWhen: 'You explain a mistake, apologise and offer a solution.',
    plan: [
      ['Greeting', 'Dear [First name],'],
      ['Purpose', "I'm really sorry about [problem]. I wanted to explain what happened."],
      ['Bullet 1', 'The reason was that [honest explanation with enough detail].'],
      ['Bullet 2', 'I realise this [effect on the reader], and I feel terrible about it.'],
      ['Bullet 3 / repair', "To make up for it, I'd like to [solution]. I hope you can forgive me."],
      ['Sign-off', 'Take care / Best wishes,\n[First name]'],
    ],
    examiner: 'Do not spend the whole letter explaining. The apology and repair must be easy to find.',
  },
  {
    title: 'Informal thanks, news or advice',
    tag: 'Friend or relative',
    useWhen: 'You thank someone, share news, give suggestions or combine these purposes.',
    plan: [
      ['Greeting', 'Dear [First name],'],
      ['Purpose', "It was great to hear from you. I'm writing to [thank you for / tell you about / give you a few ideas about] [topic]."],
      ['Bullet 1', '[Develop the first bullet with a specific detail or short example].'],
      ['Bullet 2', 'As for [second point], I think you should/could [advice], mainly because [reason].'],
      ['Bullet 3', '[Develop the final point and add an appropriate personal reaction or next step].'],
      ['Sign-off', 'All the best / See you soon,\n[First name]'],
    ],
    examiner: 'Let the relationship control the tone; do not force formal linking words into a letter to a close friend.',
  },
]

export const task2Templates = [
  {
    title: 'Agree or disagree',
    tag: 'Opinion',
    useWhen: 'The prompt asks whether you agree, disagree, or to what extent.',
    plan: [
      ['Introduction', '[Paraphrase the issue in one clear sentence]. State exactly how far you agree or disagree, then give the two main reasons that will shape the essay.'],
      ['Body 1', '[Main claim]. Explain why it is true or important, show the consequence, and add a realistic example or scenario. Keep the paragraph centred on this one idea.'],
      ['Body 2', '[Second main claim]. Develop the logic in the same way. If a concession is useful, acknowledge it briefly and explain why it does not change your overall position.'],
      ['Conclusion', 'Restate your degree of agreement and summarise the decisive reason(s) in one or two sentences. Do not introduce a new point.'],
    ],
    examiner: 'A Band 8 response sounds decisive rather than memorised: keep the position consistent, develop fewer ideas more fully, and avoid forcing balance when the task does not require it.',
  },
  {
    title: 'Discuss both views + opinion',
    tag: 'Two views',
    useWhen: 'The task explicitly asks you to discuss two positions and give your view.',
    plan: [
      ['Introduction', '[Paraphrase the debate]. Present both positions briefly and state which view you find more convincing, without using an empty sentence such as “This essay will discuss both views”.'],
      ['Body 1', 'Explain [view A] fairly. Give its strongest reason, show why supporters find it persuasive, and illustrate the likely effect with a realistic example or scenario.'],
      ['Body 2', 'Explain [view B], then make the comparison that supports your own judgement. The evaluation should grow naturally from the explanation rather than appear only in the final sentence.'],
      ['Conclusion', 'State which side is more convincing and give the main reason. Keep the conclusion short and balanced in tone.'],
    ],
    examiner: 'Do not caricature the side you disagree with. Strong Task Response comes from explaining both positions fairly and making your own view clear throughout.',
  },
  {
    title: 'Advantages and disadvantages',
    tag: 'Two sides',
    useWhen: 'The prompt asks you to explain benefits and drawbacks without asking which outweighs the other.',
    plan: [
      ['Introduction', '[Paraphrase the development]. Indicate that it has meaningful benefits as well as drawbacks, without adding an overall judgement unless the question asks for one.'],
      ['Body 1', 'Develop one main advantage, or two closely related advantages. For each, explain the mechanism and practical effect instead of simply listing benefits.'],
      ['Body 2', 'Develop the main disadvantage(s) in the same way: claim -> why -> consequence -> realistic illustration.'],
      ['Conclusion', 'Summarise the most important benefit and drawback briefly. Do not introduce a new evaluation if the task did not request one.'],
    ],
    examiner: 'Depth is more valuable than a long list. Group related ideas and make each paragraph do one clear job.',
  },
  {
    title: 'Do the advantages outweigh the disadvantages?',
    tag: 'Comparative judgement',
    useWhen: 'You must discuss both sides and decide which is more important.',
    plan: [
      ['Introduction', '[Paraphrase the development]. Make the judgement immediately: although [weaker side] matters, the [stronger side] is more significant because [decisive comparison].'],
      ['Body 1', 'Develop the weaker side fairly. Explain its real effect, then show why its scale, duration, reach, or reversibility is limited compared with the stronger side.'],
      ['Body 2', 'Develop the stronger side in depth and make the comparison explicit. Show why this effect matters more in practice, not simply that another advantage/disadvantage exists.'],
      ['Conclusion', 'Repeat the overall judgement and the key basis for comparison in one concise sentence.'],
    ],
    examiner: '“Outweigh” is a comparison task. The essay should compare significance, not merely give one paragraph to advantages and one to disadvantages.',
  },
  {
    title: 'Problems/causes and solutions',
    tag: 'Cause-effect',
    useWhen: 'The prompt asks why a problem happens, what problems it creates, how to solve it, or a combination.',
    plan: [
      ['Introduction', '[Paraphrase the issue]. Answer the exact question by identifying the main cause/problem and the broad direction of the solution.'],
      ['Body 1', 'Identify one or two root causes or major problems. Explain the mechanism clearly: what creates the issue, who is affected, and what follows from it.'],
      ['Body 2', 'Match each solution to something identified above. Name a realistic actor, the action they should take, and why that action would reduce the cause or problem.'],
      ['Conclusion', 'Summarise the central cause/problem and the matched response. Keep it brief and avoid adding a fresh proposal.'],
    ],
    examiner: 'Causes, problems, and solutions are different jobs. A strong solution is specific about who acts, what they do, and why it would work.',
  },
  {
    title: 'Two-part questions',
    tag: 'Direct questions',
    useWhen: 'Two separate questions follow the prompt, such as “Why?” and “Is this positive?”.',
    plan: [
      ['Introduction', '[Paraphrase the topic]. Give a direct answer to both questions so the direction of the essay is clear from the start.'],
      ['Body 1', 'Answer the first question with one well-developed idea. Explain the reason or mechanism, then add a concrete illustration or consequence.'],
      ['Body 2', 'Answer the second question with similar depth. If it requires an opinion, state the judgement clearly rather than implying it.'],
      ['Conclusion', 'Compress the answers to both questions into one or two sentences.'],
    ],
    examiner: 'Give both questions adequate coverage. A strong answer does not spend most of the essay on the easier half of the task.',
  },
  {
    title: 'Positive or negative development',
    tag: 'Evaluation',
    useWhen: 'The task asks whether a trend or change is positive or negative.',
    plan: [
      ['Introduction', '[Paraphrase the trend]. State whether it is largely positive or negative and identify the main effects that determine that judgement.'],
      ['Body 1', 'Develop the strongest effect supporting your judgement. Explain why it occurs, who it affects, and what practical consequence follows.'],
      ['Body 2', 'Develop the second decisive effect. Acknowledge the weaker side briefly if it makes the evaluation more credible, then explain why your overall judgement still stands.'],
      ['Conclusion', 'Restate the overall evaluation and the decisive impact(s) without repeating the introduction word for word.'],
    ],
    examiner: 'Evaluate the development itself. Do not drift into a causes essay or a simple list of pros and cons.',
  },
  {
    title: 'Mixed expository + opinion',
    tag: 'Information and judgement',
    useWhen: 'One question asks for reasons/effects and another asks what should happen or what you think.',
    plan: [
      ['Introduction', '[Paraphrase the topic]. Answer the factual part directly and state your judgement or recommendation for the opinion part.'],
      ['Body 1', 'Handle the explanatory part first: make one clear claim, explain the mechanism, and illustrate the effect with a realistic example or scenario.'],
      ['Body 2', 'Handle the opinion or recommendation part explicitly. Explain why your proposal or judgement follows from the problem described above and what result it is likely to produce.'],
      ['Conclusion', 'Summarise the explanation and the resulting judgement in a concise final statement.'],
    ],
    examiner: 'Make the shift from explanation to judgement visible, but keep the essay cohesive by showing how the second part follows from the first.',
  },
]
